# Imports

In [1]:
from imports import *
import prepare as prep

%matplotlib inline


# Decision Tree

## 1 - Split


In [2]:
# train, validate, test = prep.tralidest(X_train,'target_column')

# X_train = train.drop(columns=['target_column'])
# y_train = train.target_column

# X_validate = validate.drop(columns=['target_column'])
# y_validate = validate.target_column

# X_test = test.drop(columns=['target_column'])
# y_test = test.target_column

## 2 - Hit

In [3]:
# clf = DecisionTreeClassifier(max_depth=3, random_state=123)

# classification algorithm: gini or entropy (information gain)  
# default is gini

## 3 - Fit

In [4]:
# clf = clf.fit(X_train, y_train)

## 4 - Pic

In [5]:
# plt.figure(figsize=(16, 9), dpi=300)
# plot_tree(clf, feature_names=X_train.columns, class_names=y_train.unique())
# plt.show()

In [ ]:
# print(export_text(clf, feature_names=X_train.columns.tolist()))

## 5 - Predict

In [ ]:
# y_pred = clf.predict(X_train)

## 6 - Proba

In [ ]:
# y_pred_proba = clf.predict_proba(X_train)

# Exercises

## !!! Please Note !!!
---
#### variable "tree_trunk" contains the following list:


>tree_trunk = [clf, y_pred, y_pred_prob, tree, conf, classi_report]


In [ ]:
titanic = prep.prep_titanic()

In [ ]:
titanic.info()

In [ ]:
df=titanic
df.info()

In [ ]:
train, validate, test = prep.tralidest(df,'survived')

In [ ]:
train.head()

In [ ]:
train, validate, test=prep.impute_mode(train, validate, test, ['age'])

In [ ]:
target='survived'
titanic_ml_data=prep.ml_data(train, validate, test, target)

## 1

In [ ]:
X_train=titanic_ml_data[0]
baseline=[0 for i in range(0,len(X_train))]
y_train=titanic_ml_data[1]

What is your baseline prediction?

- $H_0: "\textrm{Does NOT survive.}"$  
- $H_1: "\textrm{Survives.}"$
---

- $TP: "\textrm{Jack (..from Titanic (..the movie.))}"$  
- $TN: "\textrm{Survivor}"$
- $FN: "\textrm{Jack in the boat.}"$
- $FP: "\textrm{Survivor in the pond.}"$


In [ ]:
X_train.head()

What is your baseline accuracy?

In [ ]:
accuracy_score(y_train,baseline)

## 2

Fit the decision tree classifier to your training sample and transform (i.e. make predictions on the training sample)

In [ ]:
titanic_clf = DecisionTreeClassifier(max_depth=3, random_state=123)

In [ ]:
titanic_clf=titanic_clf.fit(X_train, y_train)

In [ ]:
labels=[str(i) for i in y_train.unique()]

In [ ]:
plt.figure(figsize=(16, 9), dpi=300)
tree=plot_tree(titanic_clf, feature_names=X_train.columns, class_names=labels, rounded=True)
plt.show()

In [ ]:
y_pred =titanic_clf.predict(X_train)
y_pred[:5]

In [ ]:
y_pred_prob=titanic_clf.predict_proba(X_train)
y_pred_prob

## 3

Evaluate your in-sample results using the model score, confusion matrix, and classification report.

In [ ]:
titanic_clf.score(X_train,y_train)

In [ ]:
print('Accuracy of Decision Tree classifier on training set: {:.2%}\n'.format(titanic_clf.score(X_train,y_train)))

In [ ]:
conf=confusion_matrix(y_train,y_pred,)
conf

In [ ]:
pd.DataFrame(classification_report(y_train, y_pred,output_dict=True))

## 4

Compute: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [ ]:
y=classification_report(y_train, y_pred)
print(y)

In [ ]:
tpr = conf[0][0] / conf[0].sum()
fpr = conf[1][0] / conf[1].sum()
tnr = conf[1][1] / conf[1].sum()
fnr = conf[0][1] / conf[0].sum()
tpr,fpr,tnr,fnr

## 5

Run through steps 2-4 using a different max_depth value.

In [ ]:
tree_trunk2=prep.decision_tree_predict(X_train, y_train,max_depth=1)

In [ ]:
clf2,conf2=tree_trunk2[0],tree_trunk2[4]

In [ ]:
clf2.score(X_train, y_train)

In [ ]:
y_pred2 =clf2.predict(X_train)
y_pred2[:5]

In [ ]:
y_pred_prob2=clf2.predict_proba(X_train)
y_pred_prob2

In [ ]:
conf=confusion_matrix(y_train,y_pred2)
conf

In [ ]:
pd.DataFrame(classification_report(y_train, y_pred2,output_dict=True))

In [ ]:
tpr2 = conf[0][0] / conf[0].sum()
fpr2 = conf[1][0] / conf[1].sum()
tnr2 = conf[1][1] / conf[1].sum()
fnr2 = conf[0][1] / conf[0].sum()
tpr2,fpr2,tnr2,fnr2

## 6

Which model performs better on your in-sample data?
- Model 1

## 7

Which model performs best on your out-of-sample data, the validate set?
- Model 2's accuracy 
- ~(Model 1, slightly, aparently due to over fitting, possibly.)


model 1

In [ ]:
titanic_clf.score(titanic_ml_data[2],titanic_ml_data[3])

In [ ]:
y_pred_val=titanic_clf.predict(titanic_ml_data[2])
len(y_pred_val)

In [ ]:
y_pred_proba_val=titanic_clf.predict_proba(titanic_ml_data[2])
y_pred_proba_val[:5]

In [ ]:
pd.DataFrame(classification_report(titanic_ml_data[3],y_pred_val,output_dict=True))

model 2

In [ ]:
clf2.score(titanic_ml_data[2],titanic_ml_data[3])

In [ ]:
y_pred_val2=clf2.predict(titanic_ml_data[2])
y_pred_val2[:5]

In [ ]:
y_pred_proba_val2=titanic_clf.predict_proba(titanic_ml_data[2])
y_pred_proba_val2[:5]

In [ ]:
pd.DataFrame(classification_report(titanic_ml_data[3],y_pred_val2,output_dict=True))

## Telco

Work through these same exercises using the Telco dataset.

In [ ]:
df=prep.prep_telco()
df.drop('customer_id',axis=1,inplace=True)
df.info()

In [ ]:
df.total_charges.replace(to_replace=[' ',''],value=np.nan,inplace=True)

In [ ]:
np.any(np.isnan(df.total_charges))

In [ ]:
np.all(np.isfinite(df.total_charges))

In [ ]:
df.monthly_charges.head()

In [ ]:
train, validate, test=prep.tralidest(df,'churn_Yes')


In [ ]:
train, validate, test=prep.impute_mode(train, validate, test, ['total_charges'])

In [ ]:
train.info()

In [ ]:
ml_data=prep.ml_data(train, validate, test, 'churn_Yes')

What is your baseline prediction?

- $H_0: "\textrm{Does NOT churn (0).}"$  
- $H_1: "\textrm{Churning (1).}"$
---
- $TP: "\textrm{Happy customer.}"$  
- $TN: "\textrm{No customer.}"$
- $FN: "\textrm{Random customer walking around the store trying to get a price check.}"$
- $FP: "\textrm{👻}"$


In [ ]:
X_train, y_train=ml_data[0],ml_data[1]

In [ ]:
baseline=[0 for i in range(0,len(X_train))]

accuracy_score(y_train,baseline)

In [ ]:
X_train.head()

In [ ]:
tree_trunk_telco=prep.decision_tree_predict(X_train, y_train,max_depth=3)

In [ ]:
conf=tree_trunk_telco[4]

tpr = conf[0][0] / conf[0].sum()
fpr = conf[1][0] / conf[1].sum()
tnr = conf[1][1] / conf[1].sum()
fnr = conf[0][1] / conf[0].sum()
tpr,fnr,fpr,tnr

## Classes

Experiment with this model on other datasets with a higher number of output classes.

In [ ]:
df=prep.prep_iris()
df.drop('species',axis=1,inplace=True)
df.info()

In [ ]:
train, validate, test = prep.tralidest(df,['versicolor','virginica'])

In [ ]:
ml_data_iris=prep.ml_data(train, validate, test,['versicolor','virginica'])

In [ ]:
X_train, y_train=ml_data_iris[0],ml_data_iris[1]

In [ ]:
y_train=y_train.astype(str)

In [ ]:
y_train=y_train.versicolor +","+ y_train.virginica

In [ ]:
y_train[:5]

In [ ]:
tree_trunk_iris=prep.decision_tree_predict(X_train, y_train,max_depth=3)

# Random Forest

## Make the thing:

In [ ]:
# rf = RandomForestClassifier(bootstrap=True, 
#                             class_weight=None, 
#                             criterion='gini',
#                             min_samples_leaf=3,
#                             n_estimators=100,
#                             max_depth=3, 
#                             random_state=123)

## Fit the thing:

In [ ]:
# rf.fit(X_train, y_train)

## Use the thing:

In [ ]:
# y_pred = rf.predict(X_train)

## Feature Importance

In [ ]:
# print(rf.feature_importances_)

## Estimate Probability

In [ ]:
# y_pred_proba = rf.predict_proba(X_train)

# Exercises

In [ ]:
df=prep.prep_titanic()
df.info()

In [ ]:
train, validate, test = prep.tralidest(df,['survived'])

In [ ]:
train, validate, test=prep.impute_mode(train, validate, test, ['age'])

In [ ]:
ml_data_titanic=prep.ml_data(train, validate, test, ['survived'])

##### $H_0: $ 0 - "customer churned" 😵

## 1

In [ ]:
rf = RandomForestClassifier(min_samples_leaf=1,
                            max_depth=10, 
                            random_state=123)

In [ ]:
rf.fit(ml_data_titanic[0], ml_data_titanic[1])

In [ ]:
y_pred_titanic=rf.predict(ml_data_titanic[0])
y_pred_titanic[:5]

In [ ]:
y_pred_proba = rf.predict_proba(ml_data_titanic[0])
y_pred_proba[:5]


In [ ]:
print(rf.feature_importances_)

## 2

In [ ]:
print('Accuracy of Random Forest classifier on training set: {:.2%}\n'
      .format(rf.score(ml_data_titanic[0], ml_data_titanic[1])))

In [ ]:
conf=pd.DataFrame(confusion_matrix(ml_data_titanic[1],y_pred_titanic))

In [ ]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic,output_dict=True))

## 3 

In [ ]:
conf_strs=conf.astype(str)

In [ ]:
top=pd.DataFrame([['TP: ','FN: '],['FP: ','TN:']])

In [ ]:
top+conf_strs

In [ ]:
tpr = conf[0][0] / conf[0].sum()
fpr = conf[1][0] / conf[1].sum()
tnr = conf[1][1] / conf[1].sum()
fnr = conf[0][1] / conf[0].sum()
tpr,fpr,tnr,fnr

In [ ]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic,output_dict=True))

## 4

In [ ]:
rf2 = RandomForestClassifier(min_samples_leaf=3,
                            max_depth=5, 
                            random_state=123)

In [ ]:
rf3 = RandomForestClassifier(min_samples_leaf=5,
                            max_depth=3, 
                            random_state=123)

In [ ]:
rf2.fit(ml_data_titanic[0], ml_data_titanic[1])

In [ ]:
rf3.fit(ml_data_titanic[0], ml_data_titanic[1])

In [ ]:
y_pred_titanic2=rf2.predict(ml_data_titanic[0])
y_pred_titanic2[:5]

In [ ]:
y_pred_titanic3=rf3.predict(ml_data_titanic[0])
y_pred_titanic3[:5]

In [ ]:
print('Accuracy of Random Forest classifier on training set 2: {:.2%}\n'
      .format(rf2.score(ml_data_titanic[0], ml_data_titanic[1])))

In [ ]:
print('Accuracy of Random Forest classifier on training set 2: {:.2%}\n'
      .format(rf3.score(ml_data_titanic[0], ml_data_titanic[1])))

In [ ]:
conf2=pd.DataFrame(confusion_matrix(ml_data_titanic[1],y_pred_titanic2))

In [ ]:
conf3=pd.DataFrame(confusion_matrix(ml_data_titanic[1],y_pred_titanic3))

In [ ]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic2,output_dict=True))

In [ ]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic3,output_dict=True))

In [ ]:
tpr = conf2[0][0] / conf2[0].sum()
fpr = conf2[1][0] / conf2[1].sum()
tnr = conf2[1][1] / conf2[1].sum()
fnr = conf2[0][1] / conf2[0].sum()
print(f" True Positive: {tpr}, False Negative: {fnr}, False Positive: {fpr}, True Negative: {tnr}")

In [ ]:
tpr = conf3[0][0] / conf3[0].sum()
fpr = conf3[1][0] / conf3[1].sum()
tnr = conf3[1][1] / conf3[1].sum()
fnr = conf3[0][1] / conf3[0].sum()
print(f" True Positive: {tpr}, False Negative: {fnr}, False Positive: {fpr}, True Negative: {tnr}")

## 5

What are the differences in the evaluation metrics?

- Interestingly, as the min leafs increases and the max depth increases, the model becomes better tuned at finding True Negatives, thusly affecting it's recall and precision.

Which performs better on your in-sample data? Why?
- Model 1 due to higher accuracy, precision and recall (possibly overfit?).

## 6

After making a few models, which one has the best performance (or closest metrics) on both train and validate?
- Model 2 has the highest accuracy.


In [ ]:
y_pred_titanic_val=rf.predict(ml_data_titanic[2])
y_pred_titanic_val[:5]

In [ ]:
y_pred_titanic2_val=rf2.predict(ml_data_titanic[2])
y_pred_titanic2_val[:5]

In [ ]:
y_pred_titanic3_val=rf3.predict(ml_data_titanic[0])
y_pred_titanic3_val[:5]

In [ ]:
print('Accuracy of random forest classifier on val set 1: {:.2f}'.format(rf.score(ml_data_titanic[2], ml_data_titanic[3])))


In [ ]:
print('Accuracy of random forest classifier on val set 2: {:.2f}'.format(rf2.score(ml_data_titanic[2], ml_data_titanic[3])))


In [ ]:
print('Accuracy of random forest classifier on val set 3: {:.2f}'.format(rf3.score(ml_data_titanic[2], ml_data_titanic[3])))


# KNN

## Make the thing:

In [ ]:
# weights = ['uniform', 'density']
# knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')


## Fit the thing:

In [ ]:
# knn.fit(X_train, y_train)

## Use the thing:

In [ ]:
# y_pred = knn.predict(X_train)

## Estimate Probability

In [ ]:
# y_pred_proba = knn.predict_proba(X_train)

# Exercises

In [2]:
df=prep.prep_titanic()
df.info()

prepping titanic
Using cached csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   survived      891 non-null    int64  
 1   age           714 non-null    float64
 2   sibsp         891 non-null    int64  
 3   parch         891 non-null    int64  
 4   fare          891 non-null    float64
 5   sex_male      891 non-null    uint8  
 6   embarked_Q    891 non-null    uint8  
 7   embarked_S    891 non-null    uint8  
 8   class_Second  891 non-null    uint8  
 9   class_Third   891 non-null    uint8  
dtypes: float64(2), int64(3), uint8(5)
memory usage: 39.3 KB


In [3]:
train, validate, test = prep.tralidest(df,['survived'])

In [4]:
train, validate, test=prep.impute_mode(train, validate, test, ['age'])

/usr/local/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:3678: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)


In [5]:
ml_data_titanic=prep.ml_data(train, validate, test, ['survived'])

##### $H_0: $ 0 - "customer churned" 😵

## 1

In [11]:
knn = KNeighborsClassifier(5)

In [12]:
knn.fit(ml_data_titanic[0], ml_data_titanic[1])

/usr/local/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [13]:
y_pred_titanic=knn.predict(ml_data_titanic[0])
y_pred_titanic[:5]

array([0, 1, 1, 1, 0])

In [14]:
y_pred_proba = knn.predict_proba(ml_data_titanic[0])
y_pred_proba[:5]


array([[0.8, 0.2],
       [0.2, 0.8],
       [0.4, 0.6],
       [0.2, 0.8],
       [0.8, 0.2]])

## 2

In [15]:
print('Accuracy of Random Forest classifier on training set: {:.2%}\n'
      .format(knn.score(ml_data_titanic[0], ml_data_titanic[1])))

Accuracy of Random Forest classifier on training set: 79.59%



In [16]:
conf=pd.DataFrame(confusion_matrix(ml_data_titanic[1],y_pred_titanic))

In [17]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic,output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.825444    0.744898   0.79588    0.785171      0.794523
recall       0.848024    0.712195   0.79588    0.780110      0.795880
f1-score     0.836582    0.728180   0.79588    0.782381      0.794967
support    329.000000  205.000000   0.79588  534.000000    534.000000

## 3 

In [18]:
conf_strs=conf.astype(str)

In [19]:
top=pd.DataFrame([['TP: ','FN: '],['FP: ','TN:']])

In [20]:
top+conf_strs

0       1
0  TP: 279  FN: 50
1   FP: 59  TN:146

In [22]:
tpr = conf[0][0] / conf[0].sum()
fpr = conf[1][0] / conf[1].sum()
tnr = conf[1][1] / conf[1].sum()
fnr = conf[0][1] / conf[0].sum()
tpr,fpr,tnr,fnr

(0.8254437869822485,
 0.25510204081632654,
 0.7448979591836735,
 0.17455621301775148)

In [23]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic,output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.825444    0.744898   0.79588    0.785171      0.794523
recall       0.848024    0.712195   0.79588    0.780110      0.795880
f1-score     0.836582    0.728180   0.79588    0.782381      0.794967
support    329.000000  205.000000   0.79588  534.000000    534.000000

## 4 / 5

In [25]:
knn2 = KNeighborsClassifier(10)

In [26]:
knn3 = KNeighborsClassifier(20)

In [28]:
knn2.fit(ml_data_titanic[0], ml_data_titanic[1])

/usr/local/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=10)

In [27]:
knn3.fit(ml_data_titanic[0], ml_data_titanic[1])

/usr/local/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=20)

In [29]:
y_pred_titanic2=knn2.predict(ml_data_titanic[0])
y_pred_titanic2[:5]

array([0, 1, 1, 1, 0])

In [30]:
y_pred_titanic3=knn3.predict(ml_data_titanic[0])
y_pred_titanic3[:5]

array([0, 1, 1, 1, 0])

In [32]:
print('Accuracy of Random Forest classifier on training set 2: {:.2%}\n'
      .format(knn2.score(ml_data_titanic[0], ml_data_titanic[1])))

Accuracy of Random Forest classifier on training set 2: 75.66%



In [31]:
print('Accuracy of Random Forest classifier on training set 2: {:.2%}\n'
      .format(knn3.score(ml_data_titanic[0], ml_data_titanic[1])))

Accuracy of Random Forest classifier on training set 2: 73.60%



In [33]:
conf2=pd.DataFrame(confusion_matrix(ml_data_titanic[1],y_pred_titanic2))

In [35]:
conf3=pd.DataFrame(confusion_matrix(ml_data_titanic[1],y_pred_titanic3))

In [36]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic2,output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.757106    0.755102  0.756554    0.756104      0.756337
recall       0.890578    0.541463  0.756554    0.716020      0.756554
f1-score     0.818436    0.630682  0.756554    0.724559      0.746358
support    329.000000  205.000000  0.756554  534.000000    534.000000

In [37]:
pd.DataFrame(classification_report(ml_data_titanic[1],y_pred_titanic3,output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.742268    0.719178  0.735955    0.730723      0.733404
recall       0.875380    0.512195  0.735955    0.693788      0.735955
f1-score     0.803347    0.598291  0.735955    0.700819      0.724627
support    329.000000  205.000000  0.735955  534.000000    534.000000

In [38]:
tpr = conf2[0][0] / conf2[0].sum()
fpr = conf2[1][0] / conf2[1].sum()
tnr = conf2[1][1] / conf2[1].sum()
fnr = conf2[0][1] / conf2[0].sum()
print(f" True Positive: {tpr}, False Negative: {fnr}, False Positive: {fpr}, True Negative: {tnr}")

 True Positive: 0.7571059431524548, False Negative: 0.24289405684754523, False Positive: 0.24489795918367346, True Negative: 0.7551020408163265


In [39]:
tpr = conf3[0][0] / conf3[0].sum()
fpr = conf3[1][0] / conf3[1].sum()
tnr = conf3[1][1] / conf3[1].sum()
fnr = conf3[0][1] / conf3[0].sum()
print(f" True Positive: {tpr}, False Negative: {fnr}, False Positive: {fpr}, True Negative: {tnr}")

 True Positive: 0.7422680412371134, False Negative: 0.25773195876288657, False Positive: 0.2808219178082192, True Negative: 0.7191780821917808


## 6

What are the differences in the evaluation metrics?

- The lower k value produce better f1-score and accuracy

Which performs better on your in-sample data? Why?
- Model 1 due to higher accuracy, precision and recall (possibly overfit?).

## 7

After making a few models, which one has the best performance (or closest metrics) on both train and validate?
- Model 2 and 3 perform better on the validate set.


In [40]:
y_pred_titanic_val=knn.predict(ml_data_titanic[2])
y_pred_titanic_val[:5]

array([0, 0, 0, 1, 0])

In [42]:
y_pred_titanic2_val=knn2.predict(ml_data_titanic[2])
y_pred_titanic2_val[:5]

array([0, 0, 0, 1, 0])

In [43]:
y_pred_titanic3_val=knn3.predict(ml_data_titanic[0])
y_pred_titanic3_val[:5]

array([0, 1, 1, 1, 0])

In [48]:
print('Accuracy of random forest classifier on val set 1: {:.2f}'.format(knn.score(ml_data_titanic[2], ml_data_titanic[3])))


Accuracy of random forest classifier on val set 1: 0.66


In [46]:
print('Accuracy of random forest classifier on val set 2: {:.2f}'.format(knn2.score(ml_data_titanic[2], ml_data_titanic[3])))


Accuracy of random forest classifier on test set 2: 0.68


In [47]:
print('Accuracy of random forest classifier on val set 3: {:.2f}'.format(knn3.score(ml_data_titanic[2], ml_data_titanic[3])))


Accuracy of random forest classifier on test set 3: 0.68
